name: Task Management CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'  # Adjust the Node.js version as needed
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
